lib/light-service/context/key_verifier.rb
This PR gets rid of the repeated code blocks for all 3 KeyVerifiers. Inheritance seemed like a good option for it.
Not sure I liked this a 100%, it would be great to receive some feedback.
=> Refactoring the KeyVerifiers to use inheritance

README.md, lib/light-service/action.rb, lib/light-service/organizer.rb, lib/light-service/version.rb, spec/acceptance/rollback_spec.rb, spec/action_expects_and_promises_spec.rb, spec/action_promised_keys_spec.rb, spec/sample/tax/calculates_order_tax_action.rb, spec/sample/tax/calculates_tax.rb, spec/sample/tax/looks_up_tax_percentage_action.rb, spec/sample/tax/provides_free_shipping_action.rb, spec/test_doubles.rb
based on https://github.com/adomokos/light-service/issues/63
=> Prefer extend

.travis.yml, light-service.gemspec
We had a couple of outdated Ruby versions, let's test against more recent editions.
=> Test against more recent version of Ruby

README.md, lib/light-service/context.rb, lib/light-service/orchestrator.rb, lib/light-service/organizer/with_reducer_log_decorator.rb, spec/acceptance/include_warning_spec.rb, spec/acceptance/skip_all_warning_spec.rb, spec/action_spec.rb, spec/context_spec.rb, spec/sample/calculates_tax_spec.rb, spec/test_doubles.rb
=> Skip remaining

README.md, lib/light-service/action.rb, lib/light-service/context.rb, spec/acceptance/fail_spec.rb
=> Fail and return - with one call

README.md, lib/light-service/orchestrator.rb, spec/acceptance/orchestrator/with_callback_spec.rb
See the README for more detail.
=> Adding `with_callback` to Orchestrators

.rubocop.yml, Rakefile, lib/light-service/context.rb, lib/light-service/context/key_verifier.rb, lib/light-service/organizer.rb, light-service.gemspec, spec/action_spec.rb
=> Upgrade to Rubocop latest

README.md
=> Add Gem Dependency and License Badges

.travis.yml, lib/light-service/organizer/with_reducer_factory.rb, light-service.gemspec, spec/spec_helper.rb
=> Upgrade Simplecov

.travis.yml
Remove old one and begin testing with newer.
=> Roll Ruby versions to newer

lib/light-service/organizer.rb, lib/light-service/testing/context_factory.rb, spec/acceptance/after_actions_spec.rb, spec/acceptance/testing/context_factory_spec.rb, spec/test_doubles.rb, spec/testing/context_factory/iterate_spec.rb, spec/testing/context_factory/reduce_if_spec.rb, spec/testing/context_factory/reduce_until_spec.rb, spec/testing/context_factory/with_callback_spec.rb, spec/testing/context_factory_spec.rb
Reverts adomokos/light-service#146
=> ContextFactory patch for Organizer methods

RELEASES.md, lib/light-service/version.rb
=> Prepare 0.11.0 version

README.md
While trying to learn the API, I found that some methods were not written exactly the way 
it should be. Is there something I'm missing here?
- Instead of `call`, use `self.call`
- Use `self.actions` instead of `actions`
BTW, I find this library useful and I've used it for a number of projects I'm working on. Keep up the good work!
=> Change how some methods are documented.

lib/light-service.rb, spec/spec_helper.rb
=> Move `require 'active_support/core_ext/string'` to gem files from test files

lib/light-service/context.rb, lib/light-service/organizer/with_reducer.rb, spec/acceptance/organizer/execute_spec.rb, spec/test_doubles.rb
=> Add an example to call an Organizer's actions from another Organizer

README.md, RELEASES.md, lib/light-service/organizer.rb, lib/light-service/organizer/with_reducer_factory.rb, lib/light-service/organizer/with_reducer_log_decorator.rb, spec/acceptance/custom_log_from_organizer_spec.rb, spec/acceptance/log_from_organizer_spec.rb, spec/spec_helper.rb
Addresses https://github.com/adomokos/light-service/issues/159
=> Per organizer logger

.rubocop.yml, light-service.gemspec
I update some gems for ruby 2.6 compatibility
=> Update some gem for ruby 2.6

README.md
I noticed a typo in the README so I fixed it.
=> ChecksFreeShipping --> ProvidesFreeShipping

README.md
=> Add download count badge

spec/sample/provides_free_shipping_action_spec.rb
=> Fix the spec description, order <=200 should not have free shipping

.travis.yml, light-service.gemspec
=> Upgrade Simplecov to latest

README.md, spec/acceptance/organizer/add_aliases_spec.rb, spec/acceptance/organizer/add_to_context_spec.rb, spec/test_doubles.rb
No logic changes, preparing a new release.
=> Add 'add_to_context' and 'add_aliases' to README with test examples

RELEASES.md
=> Prepare v.0.13.0 release

RELEASES.md, lib/light-service/version.rb
=> Prepare release 0.14.0

.travis.yml, README.md
=> Upload coverage report to codecov.io, display Codecov badge

.travis.yml, light-service.gemspec, spec/spec_helper.rb
This should take care of sending coverage report to codecov.io.
=> Add CodeCov gem as a development dependency

RELEASES.md, lib/light-service/version.rb
No logic changes.
//cc: @gee-forr.
=> Prepare 0.2.0 release

RELEASES.md, lib/light-service/version.rb
=> 0.2 is taken, 0.20 is a no go, just use version 0.15

.travis.yml, light-service.gemspec
=> Drop Ruby 2.4, test the gem on 2.5, 2.6, 2.7 latest

RELEASES.md, lib/light-service/version.rb
//cc @gee-forr and @jaredsmithse. Thanks for your contributions!
=> Prepare v0.16.0 release

lib/light-service/action.rb
Rubocop methodlength error is a good indication that the encapsulated
logic in a method is too much. The first step of understanding the
dependencies is to extract logic into a function, this is what I am
doing with this commit.
=> Extract function from executed macro

README.md
Add another implementation to the list
=> Add light-service.js by @douglasgreyling to implementations in README
