lib/light-service/action.rb, lib/light-service/context/key_verifier.rb, spec/organizer_spec.rb, spec/test_doubles.rb
Happens when the an organizer-action rescues errors and a child action raises an exception before being able to set a promised key.
Fix is to not rely on the context's `current_action`, which is overwritten every time an action is executed.
=> Do not raise a sub-context's error

.travis.yml, README.md, lib/light-service/organizer/with_reducer.rb, lib/light-service/organizer/with_reducer_log_decorator.rb, spec/acceptance/around_each_spec.rb, spec/organizer/with_reducer_spec.rb, spec/test_doubles.rb
The ambition of this commit is to unobtrusively
gather arbitrary metrics from your application.
An around_each receiver follows the duck type of:
```ruby
def call(action, context)
```
The rest is up to you!
Here is an example that could be used to check persisted counts in a
data pipeline (there is another example in the README for logging
duration or profiling actions):
```ruby
class DataCounterCheck
def self.call(action, context)
before_count = context.data.count
result = yield
after_count = context.persisted_data.count
LightService::Configuration.logger.info({
:action       => action,
:before_count => before_count,
:after_count  => after_count,
:difference   => before_count - after_count,
})
result
end
end
```
I tried to focus most on the readability of the API, and I think it reads …
=> Adds around_each to WithReducers for organizers

README.md
Should fix issues created by #83. I thought the images would work if it's relative to your github page. Looks like it's not.
=> Make relative links absolute to fix project page

.rubocop.yml, lib/light-service/version.rb, light-service.gemspec, spec/acceptance/message_localization_spec.rb, spec/acceptance/rollback_spec.rb, spec/organizer_key_aliases_spec.rb
It won't work with AS 5.0. Specifying `"< 5.0"` in gemspec for now. Issue to support it has been created: #86.
=> Not yet ready for ActiveSupport 5 yet

lib/light-service/organizer.rb, spec/acceptance/add_numbers_spec.rb, spec/acceptance/around_each_spec.rb, spec/acceptance/message_localization_spec.rb, spec/acceptance/not_having_call_method_warning_spec.rb, spec/acceptance/rollback_spec.rb, spec/organizer_key_aliases_spec.rb, spec/organizer_spec.rb, spec/sample/calculates_tax_spec.rb, spec/sample/tax/calculates_tax.rb, spec/test_doubles.rb
As we are getting closer to introduce Orchestrators, the naming standard will be this:
```
Orchestrators
|-> run
Organizers
|-> call
Actions
|-> execute
```
It could take some practice of giving good names to Organizers, but
the method name should not be part of describing that. Also, this
convention will help the developers to figure out where an Orchestrator,
an Organizer, and Action is called.
This will go under version 0.7.
=> Issuing a Warning when the Organizer does not have a 'call' method

Rakefile
`bundle exec rake` will run all the specs and run Rubocop against
the files we are monitoring. This is what essentially the CI server
does as well, it will be easy to test before pushing the latest
commit(s) to GH.
=> Run RSpec and Rubocop with Rake

lib/light-service/action.rb
I noticed we have the `expected_keys` and `promised_keys` initialization
logic twice, removing the duplication with this commit.
=> DRY up expects and promises key initializeation logic

lib/light-service/orchestrator.rb, light-service.gemspec, spec/acceptance/orchestrator/context_failure_and_skipping_spec.rb, spec/acceptance/orchestrator/execute_spec.rb, spec/acceptance/orchestrator/iterate_spec.rb, spec/acceptance/orchestrator/reduce_if_spec.rb, spec/acceptance/orchestrator/reduce_until_spec.rb
When context is failed or set to skip remaining.
=> Short circuit orchestrator methods

lib/light-service/context/key_verifier.rb
This PR simplifies the verifiers used to check that expected keys exist, that expected keys are used and that promised keys are created.  It does a few things:
* Verifiers are expected to return a list of `offending_keys`.  If there are keys in the list, an error will be raised.
* A default formatting for `offending_keys` is provided, as is a default error message.
* An instance method `throw_error?` is used instead of `throw_error_predicate`.
* Duplicated code has been moved to the superclass, but a Verifier is free to override any necessary methods.
=> Refactor KeyVerifiers

lib/light-service/configuration.rb, lib/light-service/organizer/with_reducer_log_decorator.rb
The ruby logger class has two forms- one with method params, and one with a
block. They are different as the block form is lazy evaulated, and only
evaulated if the log level is actually enabled.
We can use this block form logger, as well as the `logger.info?` guard, to save
ourselves from building several log messages if we aren't actually going to
send or print them somewhere. This should have no effect whatsoever on the
contents of logs, it simply saves the overhead of string operations if we
aren't actually logging.
http://brian.pontarelli.com/2006/07/03/ruby-logging-and-performance/
=> Make logging more efficient if it isn't turned on

lib/light-service/context.rb, spec/context_spec.rb
Hash#fetch outputs a warning if the arg count is 2 and a block is given.
It's not possible to just pass a block without this change as the `key` and `default_or_block` arguments are always passed to the parent method.
Checking if there is a block and only passing the default if there is no block stops the warning message from showing.
=> Only pass default argument to Hash#fetch in context if no block given

spec/test_doubles.rb
The `ctx.fail!('error message')` returns the context implicitly, no need
to return from the calling code.
=> No need to return when context fails

README.md
Passing `action` as a separate parameter causes an argument error because around_each expects only one argument.
See also: https://github.com/adomokos/light-service/blob/a207d17296d9ff995e39ddeb12ed039159a11606/spec/test_doubles.rb#L54
=> Remove extra argument from example

lib/light-service/organizer/with_reducer.rb, spec/organizer_spec.rb, spec/test_doubles.rb
Rather than passing the return of each action call to the subsequent action, organizers now call each action with the same context, allowing actions to mutate the same context action.
Am mainly opening this up for discussion as this _feels_ like a pretty fundamentally breaking change.
The issue this solves for is when an organizer is within another organizer as an action the action proceeding this organizer will be called with the return from `call` rather than the context object. This will of course then fail because the action is being called with something other than a `LightService::Context`.
=> Organizers call each action with the same context

RELEASES.md, lib/light-service/context.rb, spec/acceptance/fail_spec.rb
=> Allow fail_and_return to receive error_code option

light-service.gemspec
We use it in tests but we also use it during runtime
Related to https://github.com/adomokos/light-service/pull/157
=> Make activesupport a runtime dependency

lib/light-service/localization_adapter.rb
=> Add two asterisks, fixes the Ruby 2.7.0 warning

.gitignore, lib/light-service/organizer.rb, spec/organizer_spec.rb, spec/test_doubles.rb
Hi @adomokos!
I'm creating this PR to potentially add two new utility methods upstream that I've found very useful in working with LightService.
The background on why I've found these useful is as follows:
1. It is common for organizers to share actions
2. I've found it quite useful to nest organizers when they perform common series of actions by adding `SomeOtherOrganizer.actions` to the list of actions in another Organizer
3. When pulling actions from another organizer directly, the module macro methods aren't executed and the actions pulled in will likely fail due to keys not in the context.
Therefore, these two simple methods allow an Organizer's actions to be effectively pulled in and executed within another Organizer.
So, instead of this pattern:
```
class OrganizerOne
extend …
```
=> Add add_to_context and add_aliases organizer methods

README.md, lib/light-service/context.rb, lib/light-service/organizer/with_reducer.rb, lib/light-service/organizer/with_reducer_factory.rb, lib/light-service/organizer/with_reducer_log_decorator.rb, spec/acceptance/organizer/iterate_spec.rb, spec/acceptance/organizer/reduce_if_spec.rb, spec/acceptance/organizer/reduce_until_spec.rb, spec/action_spec.rb, spec/organizer_spec.rb
Hi there,
TL;DR - Context's now have an `#organized_by` attr.
We recently came across an issue where we were using actions directly, outside of an organizer. When they failed, and triggered a roll back (like when they're used with an organizer), they instead raise an `FailWithRollbackError` exception, which is used internally by LS for managing roll back flow.
This is fine, but there are times when we need to just call the action directly. Rather than duplicate the action, and make it fail without a rollback, I added the ability for a context to know if it's part of an organized run, or a single action.
We can then put an (admittedly ugly) if/else block and fail it differently depending on whether or not the action is called directly or from an organizer.
Hope you like, please let me know …
=> Add `organized_by` into context

light-service.gemspec
This version is not even tested as of [this PR](https://github.com/adomokos/light-service/pull/197).
=> We are not supporting Active Support >= 3.0

lib/light-service/action.rb, spec/acceptance/after_actions_spec.rb
I came across a bug where the `current_action` is not changed back correctly after invoking callbacks. This has the consequence of any kind of after action callbacks not having the correct `current_action` set.
For the test that was added, if you add `puts ctx.current_action` to the `after_actions` hook, you'll get the following printout:
```
TestDoubles::IncrementCountAction
TestDoubles::AddToTotalAction
TestDoubles::IncrementCountAction
TestDoubles::AddToTotalAction
TestDoubles::IncrementCountAction
TestDoubles::AddToTotalAction
TestDoubles::AddToTotalAction
```
You'll see the last action is printed twice. That's because the very last one should have `TestDoubles::IterateCollectionAction` as it's `:current_action` instead of a duplicate `TestDoubles::AddToTotalAction`. 
I took a stab at …
=> 🐛 Fix callback current action

README.md, lib/light-service/action.rb, lib/light-service/errors.rb, spec/action_optional_expected_keys_spec.rb, spec/test_doubles.rb
This PR extends the `expects` macro so that a default value can be supplied. When an expected key's value is not supplied, and there is a default, it will be used instead, and a `LightService::ExpectedKeysNotInContextError` will be avoided.
I've implemented support for both static default values and dynamic defaults. Dynamic defaults accept a callable that takes the context as a param.
Full documentation on how to use this feature is included. Tests are also included.
This should also resolve #215. It does also obsolete https://github.com/adomokos/light-service/pull/216 unfortunately.
Hope you like it :)
=> Implement support for default values for optional expected keys

lib/light-service/testing/context_factory.rb, spec/test_doubles.rb, spec/testing/context_factory_spec.rb
I've tried to update one of our project to ruby 3.0 and the only issue was in our services spec using ContextFactory.
We use named argument a lot and 3.0 break this when they're not passed explicitly using the double splat operator. `ruby2_keywords` marks the method as using the old style of named arguments. Calling it this way should works with older 2.x versions as well.
=> Support for named argument in ruby 3

.github/workflows/project-build.yml, README.md, lib/light-service/deprecation_warning.rb, light-service.gemspec, spec/spec_helper.rb
This got lost when I moved the CI from Travis to GitHub action. Let's use it again!
=> Re-enable simplecov and codecov coverage analysis

.github/workflows/project-build.yml
This PR uses the `bundler-cache` feature of the Ruby-maintained Action `ruby/setup-ruby`.
[See `ruby/setup-ruby` parameters declaration](https://github.com/ruby/setup-ruby/blob/master/action.yml) for more information.
=> CI: trust bundler: cache

README.md, lib/light-service/i18n/localization_adapter.rb, lib/light-service/localization_adapter.rb, spec/context_spec.rb
This PR refactors the `LocalizationAdapter` and `I18n::LocalizationAdapter` classes to standardize the method interfaces for `success` and `failure`. The changes aim to unify how these methods are called and processed, regardless of which adapter is used.
1. **Unified Method Signature**:
- Both `success` and `failure` methods now accept a third optional `options` argument in both `LocalizationAdapter` and `I18n::LocalizationAdapter`.
2. **Improved Extensibility**:
- The added `options` argument allows for future extensibility without requiring interface changes.
- To create a unified interface for both adapters, simplifying their usage and improving maintainability.
- To provide flexibility for passing additional options (like `i18n_options`) without breaking existing functionality.
- If …
=> Fix argument errors of LightService::LocalizationAdapter

README.md, lib/light-service.rb, lib/light-service/context.rb, light-service.gemspec
We are not ready to remove it. There are instances of `blank?` and `singularize` that are used in the code.
Removing `activesupport` still not fails any of the tests, as we have `generator_spec` that uses and installs `activesupport`.
Fixes #257  and #258.
=> Add back activesupport

lib/light-service/organizer/verify_call_method_exists.rb, spec/acceptance/not_having_call_method_warning_spec.rb
To address #264 
Disclaimer: I've never touched this repo so I might be missing something. I needed to update some other gems in one of my employers apps and found they were still on a 2017 version of this gem so I bumped it and that led me here. 
I was getting this when trying to run rspec on our app
```
NoMethodError:
undefined method `deprecation_warning' for LightService:Module
LightService.deprecation_warning(warning_msg)
^^^^^^^^^^^^^^^^^^^^
Did you mean?  deprecate_constant
```
and this is where I wound up tracing it to.
Thanks!
=> change deprecation_warning method call

light-service.gemspec
It will not be in future versions of Ruby.
Fixes #266.
=> Add ostruct as development dependency

light-service.gemspec
/lib/active_support/core_ext/benchmark.rb:3: warning: benchmark was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add benchmark to your Gemfile or gemspec to silence this warning.
Fixes #267
=> Fix benchmark warning

README.md
Even though based on a previous bug report it seems as if this is not the intended behavior, it hasn't been addressed and the docs should reflect the current state not to confuse others.  I spent a little while debugging an issue around this and it'd be good to spare others that same frustration until a fix can be implemented.
=> Update README.md to reflect before and after actions do not execute on every call to an organizer.
